FROM mcr.microsoft.com/dotnet/runtime:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["cs anime fetcg/cs anime fetcg.csproj", "cs anime fetcg/"]
RUN dotnet restore "cs anime fetcg/cs anime fetcg.csproj"
COPY . .
WORKDIR "/src/cs anime fetcg"
RUN dotnet build "cs anime fetcg.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "cs anime fetcg.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "cs anime fetcg.dll"]
